/** Quiet Materiality — 사용자 계정과 설정을 단정한 패널로 제공하고 관리자 화면에 접근시키는 계정 영역. */

import { AppShell } from "@/components/AppShell";
import { PageTitle, Tag } from "@/components/InteriorPieces";
import { USER } from "@/data/mockData";
import { useInspira } from "@/contexts/InspiraContext";
import { BellRing, ChevronRight, KeyRound, LayoutDashboard, LogOut, Mail, Settings2, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

export function ProfilePage() { const { favoriteConceptIds, favoriteMaterialIds, favoriteProjectIds } = useInspira(); return <AppShell><div className="page-enter mx-auto max-w-[950px]"><PageTitle eyebrow="마이페이지" title="김인스님의 공간 아카이브" description="저장한 프로젝트와 취향을 한 곳에서 관리할 수 있어요." /><section className="premium-panel overflow-hidden"><div className="bg-[#2b2824] px-6 py-8 text-white sm:px-8"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-full border-4 border-white/15 bg-[#d6b998] text-xl font-semibold text-[#4d3927]">김</span><div><p className="text-[11px] text-[#d2c6b7]">{USER.role}</p><h2 className="mt-1 font-display text-[26px] font-semibold">{USER.name}님</h2><p className="mt-1 text-[11px] text-[#d2c6b7]">{USER.email}</p></div></div></div><div className="grid grid-cols-3 divide-x divide-[#eee9e1] p-5 text-center">{[["저장한 시안", favoriteConceptIds.length], ["저장한 자재", favoriteMaterialIds.length], ["프로젝트", favoriteProjectIds.length]].map(([label, value]) => <div key={String(label)}><p className="font-display text-[23px] font-semibold text-[#3e372e]">{value}</p><p className="mt-1 text-[10px] text-[#92897e]">{label}</p></div>)}</div></section><section className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/settings" className="premium-panel flex items-center gap-3 p-4 hover:bg-white"><span className="grid size-9 place-items-center rounded-xl bg-[#eee6da] text-[#594633]"><Settings2 size={17} /></span><span className="flex-1"><strong className="block text-[11px] text-[#4a433a]">계정 설정</strong><small className="mt-1 block text-[10px] text-[#92897d]">알림, 기본 취향, 계정 정보</small></span><ChevronRight size={15} className="text-[#9d9489]" /></Link><Link href="/favorites" className="premium-panel flex items-center gap-3 p-4 hover:bg-white"><span className="grid size-9 place-items-center rounded-xl bg-[#eee6da] text-[#594633]"><UserRound size={17} /></span><span className="flex-1"><strong className="block text-[11px] text-[#4a433a]">저장한 항목</strong><small className="mt-1 block text-[10px] text-[#92897d]">시안, 자재, 프로젝트 보관함</small></span><ChevronRight size={15} className="text-[#9d9489]" /></Link></section></div></AppShell>; }

export function SettingsPage() { const { setAuthenticated } = useInspira(); const [, navigate] = useLocation(); return <AppShell><div className="page-enter mx-auto max-w-[850px]"><PageTitle eyebrow="설정" title="서비스 환경을 설정하세요." description="현재 버전은 Mock Data로 작동하며, 실제 API와 인증 연결을 고려한 인터페이스를 제공합니다." /><div className="space-y-4"><section className="premium-panel p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#eee6da] text-[#594633]"><BellRing size={17} /></span><div><h2 className="text-[12px] font-semibold">알림 설정</h2><p className="mt-1 text-[10px] text-[#90877c]">시안 생성 완료와 즐겨찾기 자재 업데이트를 알려드립니다.</p></div><button onClick={() => toast.success("알림 수신 설정이 저장되었어요.")} className="ml-auto rounded-lg bg-[#2b2925] px-3 py-2 text-[10px] font-semibold text-white">켜짐</button></div></section><section className="premium-panel p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#eee6da] text-[#594633]"><KeyRound size={17} /></span><div><h2 className="text-[12px] font-semibold">연결 및 보안</h2><p className="mt-1 text-[10px] text-[#90877c]">향후 AI API, 자재 DB, 인증 서비스를 연결할 수 있도록 준비되어 있어요.</p></div><Tag className="ml-auto">준비 중</Tag></div></section><Link href="/admin" className="premium-panel flex items-center gap-3 p-5 hover:bg-white"><span className="grid size-9 place-items-center rounded-xl bg-[#eee6da] text-[#594633]"><ShieldCheck size={17} /></span><div className="flex-1"><h2 className="text-[12px] font-semibold">관리자 페이지</h2><p className="mt-1 text-[10px] text-[#90877c]">Mock Data 기반의 자재·브랜드·AI 요청 관리 화면</p></div><ChevronRight size={15} className="text-[#9d9489]" /></Link><button onClick={() => { setAuthenticated(false); navigate("/"); }} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#e4ded7] bg-white px-4 py-3 text-[11px] font-semibold text-[#6d6257]"><LogOut size={14} /> 로그아웃</button></div></div></AppShell>; }
