/** Quiet Materiality — 브랜드의 표면 언어와 등록된 자재를 에디토리얼 카드로 보여 주는 브랜드 페이지. */

import { AppShell } from "@/components/AppShell";
import { MaterialGridCard, PageTitle, Tag } from "@/components/InteriorPieces";
import { BRANDS, MATERIALS } from "@/data/mockData";
import { ArrowLeft, ArrowUpRight, ChevronRight, Layers3, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";

export default function BrandsPage() { const [, params] = useRoute("/brands/:id"); if (params?.id) return <BrandDetail brandId={params.id} />; return <BrandIndex />; }

function BrandIndex() { return <AppShell><div className="page-enter mx-auto max-w-[1180px]"><PageTitle eyebrow="07 · 브랜드" title="공간을 만드는 브랜드의 언어를 만나보세요." description="마루부터 필름, 가구와 조명까지. 시안 속 분위기를 이어갈 수 있는 브랜드별 자재를 둘러보세요." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{BRANDS.map((brand, index) => <Link href={`/brands/${brand.id}`} key={brand.id} className="group relative overflow-hidden rounded-[19px] border border-[#e7e2da] bg-white p-5 shadow-[0_8px_22px_rgba(72,57,40,.035)] transition-transform hover:-translate-y-0.5"><span className="absolute -right-7 -top-10 size-32 rounded-full opacity-40" style={{ background: brand.color }} /><div className="relative"><span className="grid size-10 place-items-center rounded-xl bg-[#292722] text-[13px] font-display font-semibold text-white">{brand.name.slice(0, 1)}</span><p className="mt-7 text-[10px] font-semibold tracking-[.1em] text-[#9c9185]">MATERIAL PARTNER 0{index + 1}</p><h2 className="mt-2 font-display text-[23px] font-semibold tracking-[-.035em] text-[#302b25]">{brand.name}</h2><p className="mt-2 text-[11px] leading-5 text-[#766e64]">{brand.headline}</p><p className="mt-4 min-h-[42px] text-[10px] leading-5 text-[#91887d]">{brand.description}</p><div className="mt-5 flex items-end justify-between border-t border-[#eeeae4] pt-4"><div><p className="text-[10px] text-[#9b9186]">등록 자재</p><p className="mt-0.5 font-display text-[20px] font-semibold text-[#463c31]">{brand.materialCount}<span className="ml-0.5 text-[10px] font-sans font-medium">items</span></p></div><span className="inline-flex items-center gap-1 text-[10px] font-bold text-[#514535]">상세 보기 <ArrowUpRight size={13} /></span></div></div></Link>)}</div></div></AppShell>; }

function BrandDetail({ brandId }: { brandId: string }) { const brand = BRANDS.find((item) => item.id === brandId) ?? BRANDS[0]; const materials = MATERIALS.filter((material) => material.brand === brand.name); return <AppShell><div className="page-enter mx-auto max-w-[1180px]"><Link href="/brands" className="mb-6 inline-flex items-center gap-1 text-[11px] font-semibold text-[#7a7166]"><ArrowLeft size={14} /> 브랜드로 돌아가기</Link><section className="relative overflow-hidden rounded-[22px] bg-[#292722] px-6 py-8 text-white sm:px-8 sm:py-10"><span className="absolute -right-10 -top-14 size-56 rounded-full opacity-75" style={{ background: brand.color }} /><div className="relative max-w-xl"><p className="text-[10px] font-semibold tracking-[.13em] text-[#d2c4b3]">MATERIAL PARTNER</p><h1 className="mt-3 font-display text-[38px] font-semibold tracking-[-.05em]">{brand.name}</h1><p className="mt-3 text-[13px] leading-6 text-[#e2d9cd]">{brand.description}</p><div className="mt-5 flex flex-wrap gap-2">{brand.categories.map((category) => <Tag key={category} className="bg-white/10 text-white">{category}</Tag>)}</div></div></section><div className="mt-9 flex items-end justify-between"><div><p className="text-[10px] font-semibold tracking-[.1em] text-[#968c81]">BRAND COLLECTION</p><h2 className="mt-1 font-display text-[24px] font-semibold">인기 제품과 최근 추가 제품</h2></div><span className="text-[11px] text-[#80776d]">Mock Data {materials.length}개</span></div>{materials.length ? <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{materials.map((material) => <MaterialGridCard key={material.id} material={material} />)}</div> : <div className="premium-panel mt-5 flex flex-col items-center py-14 text-center"><Layers3 size={22} className="text-[#92877a]" /><p className="mt-3 text-[12px] font-semibold">브랜드 자재 데이터를 준비 중이에요.</p><p className="mt-1 text-[10px] text-[#948b80]">현재 라이브러리에 매칭된 예시 자재가 없습니다.</p></div>}</div></AppShell>; }
