/** Quiet Materiality — 한 공간에서 출발한 다섯 시안을 갤러리 카드로 안내하는 결과 리스트. */

import { AppShell } from "@/components/AppShell";
import { ConceptCard, PageTitle, Tag } from "@/components/InteriorPieces";
import { DESIGN_CONCEPTS, PROJECTS } from "@/data/mockData";
import { ArrowLeft, PencilLine, Plus, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function ConceptsPage() { const [location] = useLocation(); const generated = new URLSearchParams(location.split("?")[1]).get("generated") === "true"; const project = PROJECTS.find((item) => item.id === new URLSearchParams(location.split("?")[1]).get("project")) ?? PROJECTS[0]; return <AppShell><div className="page-enter mx-auto max-w-[1180px]">{generated && <div className="mb-6 flex items-center gap-2 rounded-xl border border-[#dfd2c0] bg-[#f4ede3] px-4 py-3 text-[11px] font-medium text-[#604f3d]"><span className="grid size-5 place-items-center rounded-full bg-[#e5d5c1]"><Sparkles size={12} /></span> 다섯 가지 시안과 유사 자재 제안이 준비되었어요.</div>}<div className="mb-6 flex items-center justify-between"><Link href="/projects" className="inline-flex items-center gap-1 text-[11px] font-semibold text-[#7a7166]"><ArrowLeft size={14} /> 프로젝트로 돌아가기</Link><div className="flex gap-2"><Link href="/project/new" className="inline-flex items-center gap-1.5 rounded-lg border border-[#e0dbd3] bg-white px-3 py-2 text-[10px] font-semibold text-[#514a41]"><Plus size={13} /> 새 시안 생성</Link><Link href="/concepts/c-01/revise" className="inline-flex items-center gap-1.5 rounded-lg bg-[#211f1b] px-3 py-2 text-[10px] font-semibold text-white"><PencilLine size={13} /> 수정 요청</Link></div></div><PageTitle eyebrow="03 · 시안 결과 리스트" title={project.title} description="AI가 제안한 인테리어 시안 5가지입니다. 마음에 드는 방향을 선택하면 자세한 자재 추천을 확인할 수 있어요." /><div className="mb-7 flex flex-wrap gap-2">{["따뜻한 느낌", "모던", "우드톤", "화이트·베이지 계열"].map((tag, index) => <Tag key={tag} dark={index === 0}>{tag}</Tag>)}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{DESIGN_CONCEPTS.map((concept) => <ConceptCard key={concept.id} concept={concept} />)}</div><div className="mt-10 flex items-center justify-between border-t border-[#e4dfd8] pt-5"><p className="text-[11px] text-[#887f74]">같은 공간 구조로 다른 분위기의 다섯 장면을 비교해 보세요.</p><Link href="/compare" className="text-[11px] font-bold text-[#4b4237] underline underline-offset-4">시안 비교하기</Link></div></div></AppShell>; }
