/** Quiet Materiality — 사용자가 저장한 시안·자재·프로젝트를 탭으로 조용히 다시 꺼내는 보관함. */

import { AppShell } from "@/components/AppShell";
import { ConceptCard, MaterialGridCard, PageTitle, ProjectCard } from "@/components/InteriorPieces";
import { DESIGN_CONCEPTS, MATERIALS, PROJECTS } from "@/data/mockData";
import { useInspira } from "@/contexts/InspiraContext";
import { Heart, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const tabs = ["시안", "자재", "프로젝트"] as const;
export default function FavoritesPage() { const [tab, setTab] = useState<typeof tabs[number]>("시안"); const { favoriteConceptIds, favoriteMaterialIds, favoriteProjectIds } = useInspira(); const items = tab === "시안" ? DESIGN_CONCEPTS.filter((item) => favoriteConceptIds.includes(item.id)) : tab === "자재" ? MATERIALS.filter((item) => favoriteMaterialIds.includes(item.id)) : PROJECTS.filter((item) => favoriteProjectIds.includes(item.id)); return <AppShell><div className="page-enter mx-auto max-w-[1180px]"><PageTitle eyebrow="08 · 즐겨찾기" title="마음에 남은 장면을 모아보세요." description="저장한 시안, 자재, 프로젝트를 한 곳에서 다시 확인할 수 있습니다." /><div className="mb-6 flex gap-1 rounded-xl border border-[#e3ded6] bg-[#f1efeb] p-1.5 w-fit">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "rounded-lg bg-white px-4 py-2 text-[11px] font-bold text-[#38332d] shadow-sm" : "rounded-lg px-4 py-2 text-[11px] font-medium text-[#827a70]"}>{item} <span className="ml-1 text-[10px]">{item === "시안" ? favoriteConceptIds.length : item === "자재" ? favoriteMaterialIds.length : favoriteProjectIds.length}</span></button>)}</div>{items.length ? <div className={tab === "프로젝트" ? "grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 lg:grid-cols-4" : tab === "자재" ? "grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4" : "grid gap-4 sm:grid-cols-2 xl:grid-cols-3"}>{tab === "시안" && (items as typeof DESIGN_CONCEPTS).map((item) => <ConceptCard key={item.id} concept={item} />)}{tab === "자재" && (items as typeof MATERIALS).map((item) => <MaterialGridCard key={item.id} material={item} />)}{tab === "프로젝트" && (items as typeof PROJECTS).map((item) => <ProjectCard key={item.id} project={item} />)}</div> : <div className="premium-panel flex flex-col items-center py-20 text-center"><span className="grid size-11 place-items-center rounded-2xl bg-[#eee6da] text-[#5c4b37]"><Heart size={20} /></span><p className="mt-4 text-[13px] font-semibold">아직 저장한 {tab}이 없어요.</p><p className="mt-2 text-[11px] text-[#897f74]">마음에 드는 항목의 하트 아이콘을 눌러 여기에 모아보세요.</p><Link href={tab === "시안" ? "/concepts" : tab === "자재" ? "/materials" : "/projects"} className="mt-5 inline-flex items-center gap-1.5 rounded-xl bg-[#211f1b] px-4 py-3 text-[11px] font-semibold text-white"><Sparkles size={13} /> 둘러보기</Link></div>}</div></AppShell>; }
