/** Quiet Materiality — 실제 작업을 기다리는 감각을 주는 순차 단계형 Mock 생성 화면. */

import { AppLogo } from "@/components/AppShell";
import { ASSET } from "@/data/mockData";
import { useInspira } from "@/contexts/InspiraContext";
import { Check, LoaderCircle, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

const stages = ["공간 구조 분석 중", "사용자 취향 분석 중", "최신 인테리어 트렌드 분석 중", "콘셉트 5개 구성 중", "실사형 시안 생성 중", "유사 자재 검색 중"];

export default function GeneratingPage() { const [active, setActive] = useState(0); const [, navigate] = useLocation(); const { createdProjectTitle } = useInspira(); useEffect(() => { const interval = window.setInterval(() => setActive((current) => current < stages.length - 1 ? current + 1 : current), 700); const finish = window.setTimeout(() => navigate("/concepts?generated=true"), 5000); return () => { window.clearInterval(interval); window.clearTimeout(finish); }; }, [navigate]); return <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#f7f5f1] px-5"><div className="absolute inset-0"><img src={ASSET.living} alt="" className="size-full object-cover opacity-[.08] blur-sm" /><div className="absolute inset-0 bg-[#f7f5f1]/80" /></div><div className="relative w-full max-w-[520px]"><div className="flex justify-center"><AppLogo /></div><div className="mt-10 rounded-[24px] border border-white/85 bg-white/90 p-6 shadow-[0_22px_60px_rgba(70,55,37,.1)] backdrop-blur sm:p-8"><div className="flex justify-center"><span className="grid size-14 place-items-center rounded-[18px] bg-[#26231f] text-white shadow-[0_10px_22px_rgba(35,31,26,.16)]"><Sparkles size={24} /></span></div><div className="mt-6 text-center"><p className="text-[10px] font-semibold tracking-[.12em] text-[#9b8b79]">AI INTERIOR DIRECTION</p><h1 className="mt-2 font-display text-[27px] font-semibold tracking-[-.04em] text-[#2b2722] sm:text-[31px]">공간에 어울리는 인테리어<br />시안을 만들고 있어요.</h1><p className="mt-3 text-[12px] leading-6 text-[#7d746a]"><strong className="font-semibold text-[#524b42]">{createdProjectTitle}</strong>의 동일한 공간 구조를 기반으로<br />서로 다른 5개의 방향을 준비합니다.</p></div><div className="mt-8 space-y-1">{stages.map((stage, index) => <div key={stage} className={index <= active ? "flex items-center gap-3 rounded-xl bg-[#f5f1eb] px-3 py-3" : "flex items-center gap-3 rounded-xl px-3 py-3 opacity-45"}><span className={index < active ? "grid size-5 place-items-center rounded-full bg-[#292722] text-white" : index === active ? "grid size-5 place-items-center text-[#5b4d3d]" : "grid size-5 place-items-center rounded-full border border-[#dcd5cc] text-transparent"}>{index < active ? <Check size={12} /> : index === active ? <LoaderCircle size={17} className="animate-spin" /> : "·"}</span><span className={index <= active ? "text-[11px] font-semibold text-[#4d463e]" : "text-[11px] text-[#827a70]"}>{stage}</span>{index === active && <span className="ml-auto text-[10px] text-[#9a8d7f]">진행 중</span>}</div>)}</div><p className="mt-6 text-center text-[10px] text-[#9c9388]">완료 후 시안 리스트 페이지로 자동 이동합니다.</p></div></div></div>; }
