/** Quiet Materiality — 넓은 여백과 자연광 이미지로 INSPIRA의 첫 장면을 구성하는 랜딩 페이지. */

import { AppLogo } from "@/components/AppShell";
import { AIChip, Eyebrow, InteriorImage, Tag } from "@/components/InteriorPieces";
import { ASSET, DESIGN_CONCEPTS } from "@/data/mockData";
import { ArrowDown, ArrowRight, Check, ChevronDown, CirclePlay, Layers3, Sparkles, SwatchBook, UploadCloud } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const faq = [
  ["어떤 이미지를 올릴 수 있나요?", "실제 공간 사진, SketchUp 캡처, 평면도 이미지 또는 PDF 도면을 업로드할 수 있습니다. 여러 장을 함께 올리면 공간의 맥락을 더 잘 반영합니다."],
  ["시안 생성에는 얼마나 걸리나요?", "프로토타입에서는 생성 흐름을 확인한 뒤 바로 시안 목록으로 이동합니다. 실제 서비스 연결 시에는 공간 분석과 이미지 생성 단계가 진행됩니다."],
  ["추천 자재는 실제 구매할 수 있나요?", "현재는 자연스러운 예시 데이터를 사용합니다. 향후 브랜드·제품 데이터 연결 후에는 실제 제품 정보와 구매 링크를 함께 제공할 수 있도록 구조화했습니다."],
  ["기존 구조나 가구를 유지할 수 있나요?", "네. 프로젝트 생성 단계에서 반드시 유지할 요소와 바꾸고 싶은 요소를 구체적으로 입력할 수 있습니다."],
];

export default function Landing() {
  const [openFaq, setOpenFaq] = useState(0);
  return <div className="min-h-screen overflow-hidden bg-[#f8f7f4] text-[#292620]">
    <header className="mx-auto flex max-w-[1480px] items-center justify-between px-5 py-5 sm:px-8 lg:px-12 lg:py-7">
      <AppLogo />
      <nav className="hidden items-center gap-8 text-[12px] font-medium text-[#6f685f] md:flex"><a href="#how">이용 방법</a><a href="#materials">자재 추천</a><a href="#faq">자주 묻는 질문</a></nav>
      <div className="flex items-center gap-2.5"><Link href="/auth" className="hidden rounded-lg px-3 py-2 text-[12px] font-semibold text-[#49433b] sm:inline-flex">로그인</Link><Link href="/auth?mode=signup" className="rounded-lg bg-[#201f1c] px-3.5 py-2.5 text-[11px] font-semibold text-white shadow-sm transition-transform active:scale-[.97] sm:px-4 sm:text-[12px]">무료로 시안 받아보기</Link></div>
    </header>

    <main>
      <section className="mx-auto grid max-w-[1480px] grid-cols-1 gap-8 px-5 pb-20 pt-8 sm:px-8 md:pt-14 lg:grid-cols-[.93fr_1.07fr] lg:gap-16 lg:px-12 lg:pb-32">
        <div className="relative z-10 flex flex-col justify-center lg:pb-5"><AIChip /><Eyebrow><span className="ml-2">공간을 위한 새로운 영감</span></Eyebrow><h1 className="mt-7 max-w-[690px] font-display text-[38px] font-semibold leading-[1.23] tracking-[-0.045em] text-[#24221e] sm:text-[51px] lg:text-[59px]">내 공간에 어울리는<br /><em className="not-italic text-[#927252]">인테리어 시안</em>을<br />제안받아보세요</h1><p className="mt-6 max-w-[520px] text-[14px] leading-7 text-[#746d63] sm:text-[15px]">공간 사진이나 도면을 업로드하면 AI가 최신 인테리어 트렌드를 반영한 5개 이상의 실사형 시안을 제안합니다.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/project/new" className="inline-flex items-center gap-2 rounded-xl bg-[#1e1d1a] px-5 py-3.5 text-[13px] font-semibold text-white shadow-[0_10px_22px_rgba(32,29,24,.18)] transition-transform active:scale-[.97]">내 공간 시안 만들기 <ArrowRight size={16} /></Link><a href="#how" className="inline-flex items-center gap-2 rounded-xl border border-[#dfdad2] bg-white px-4 py-3.5 text-[12px] font-semibold text-[#4b443b] transition-colors hover:bg-[#fbfaf8]"><CirclePlay size={16} strokeWidth={1.6} /> 어떻게 작동하나요?</a></div><div className="mt-11 flex items-center gap-6 border-t border-[#e7e2da] pt-5"><div><p className="font-display text-[20px] font-semibold">5+</p><p className="mt-0.5 text-[10px] text-[#897f74]">서로 다른 시안 제안</p></div><div className="h-8 border-l border-[#e6e0d8]" /><div><p className="font-display text-[20px] font-semibold">1곳</p><p className="mt-0.5 text-[10px] text-[#897f74]">나만의 실제 공간 기반</p></div><div className="h-8 border-l border-[#e6e0d8]" /><div><p className="font-display text-[20px] font-semibold">∞</p><p className="mt-0.5 text-[10px] text-[#897f74]">자재 조합의 가능성</p></div></div></div>
        <div className="relative min-h-[390px] sm:min-h-[510px] lg:min-h-[620px]"><div className="absolute -right-20 top-5 size-[310px] rounded-full bg-[#eee3d4] blur-3xl" /><InteriorImage src={ASSET.living} alt="웜 미니멀 거실 인테리어" priority className="absolute inset-x-0 top-0 h-[89%] rounded-[24px] shadow-[0_25px_60px_rgba(68,51,35,.16)]" /><div className="absolute -bottom-2 left-4 flex max-w-[245px] items-center gap-3 rounded-[16px] border border-white/80 bg-white/92 p-3 shadow-[0_12px_28px_rgba(75,61,42,.14)] backdrop-blur sm:bottom-3 sm:left-6"><InteriorImage src={ASSET.luxury} alt="모던 럭셔리 미리보기" className="size-14 shrink-0 rounded-[10px]" /><div><p className="text-[10px] text-[#8e857a]">AI가 제안한 첫 번째 방향</p><p className="mt-1 text-[12px] font-bold text-[#302b25]">웜 미니멀</p><div className="mt-1 flex gap-1"><Tag>라이트 오크</Tag><Tag>아이보리</Tag></div></div></div><span className="absolute -right-1 top-[16%] grid size-12 place-items-center rounded-full border border-white/70 bg-white/92 text-[#26231f] shadow-sm backdrop-blur"><Sparkles size={19} /></span></div>
      </section>

      <section id="how" className="border-y border-[#e8e3db] bg-[#fcfbf9]"><div className="mx-auto max-w-[1480px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="max-w-[520px]"><Eyebrow>How it works</Eyebrow><h2 className="mt-3 font-display text-[30px] font-semibold tracking-[-.035em] sm:text-[38px]">공간을 읽고, 취향을 더해<br />당신만의 방향을 제안합니다.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3"><ProcessCard number="01" icon={UploadCloud} title="공간을 올려주세요" desc="사진, SketchUp 캡처 또는 도면으로 현재 공간의 구조를 알려주세요." /><ProcessCard number="02" icon={SwatchBook} title="원하는 결을 고르세요" desc="선호하는 스타일과 색감, 남기고 싶은 요소를 차분히 입력합니다." /><ProcessCard number="03" icon={Layers3} title="시안과 자재를 함께 보세요" desc="같은 공간에서 출발한 다섯 가지 장면과 실제 자재 조합을 확인합니다." /></div></div></section>

      <section id="materials" className="mx-auto max-w-[1480px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div className="relative grid grid-cols-2 gap-3"><InteriorImage src={ASSET.bedroom} alt="내추럴 호텔 침실 시안" className="aspect-[.9] rounded-[19px]" /><InteriorImage src={ASSET.study} alt="웜 그레이 서재 시안" className="mt-14 aspect-[.9] rounded-[19px]" /><div className="absolute inset-x-[18%] bottom-3 rounded-[17px] border border-white/70 bg-white/90 p-4 shadow-[0_12px_30px_rgba(71,57,38,.12)] backdrop-blur"><p className="text-[10px] font-semibold text-[#82786c]">한 장면을 더 현실적으로 만드는 것</p><div className="mt-3 flex items-center gap-2"><span className="size-8 rounded-lg bg-[linear-gradient(135deg,#d8b985,#b98751)]" /><span className="size-8 rounded-lg bg-[linear-gradient(135deg,#f3eee4,#ddd4c5)]" /><span className="size-8 rounded-lg bg-[linear-gradient(135deg,#a89c8f,#70675f)]" /><p className="ml-1 text-[11px] font-semibold text-[#37312a]">유사 자재 추천</p></div></div></div><div><Eyebrow>Material direction</Eyebrow><h2 className="mt-3 font-display text-[31px] font-semibold leading-[1.35] tracking-[-.04em] sm:text-[40px]">이미지 속 질감과 닮은<br />실제 자재를 함께.</h2><p className="mt-5 max-w-md text-[14px] leading-7 text-[#736c63]">마루, 벽지, 필름, 가구와 조명까지. 시안의 색온도와 표면감을 기준으로, 공간의 분위기를 이어갈 수 있는 자재를 함께 제안합니다.</p><ul className="mt-7 space-y-3">{["자재 카테고리와 브랜드·품번을 한눈에", "색상·재질·추천 이유를 시안과 연결해", "프로젝트별 자재 리스트를 저장하고 비교"].map((item) => <li key={item} className="flex items-center gap-3 text-[12px] font-medium text-[#4d473f]"><span className="grid size-5 place-items-center rounded-full bg-[#eee4d7] text-[#5c4d3c]"><Check size={12} /></span>{item}</li>)}</ul><Link href="/materials" className="mt-8 inline-flex items-center gap-2 text-[12px] font-bold text-[#332e26] underline decoration-[#cfc4b3] underline-offset-4">자재 라이브러리 미리 보기 <ArrowRight size={15} /></Link></div></div></section>

      <section className="bg-[#25231f] text-white"><div className="mx-auto grid max-w-[1480px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-28"><div><Eyebrow><span className="text-[#c9b89e]">Five directions, one room</span></Eyebrow><h2 className="mt-3 font-display text-[30px] font-semibold leading-[1.35] tracking-[-.04em] sm:text-[38px]">같은 공간으로부터<br />서로 다른 다섯 장면.</h2><p className="mt-5 max-w-sm text-[13px] leading-7 text-[#c2bcb2]">한 가지 답을 강요하지 않습니다. 내 공간의 구조는 유지하면서, 당신이 선택할 수 있는 여러 가지 결을 만듭니다.</p><Link href="/concepts" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-[12px] font-bold text-[#2b2924] transition-transform active:scale-[.97]">시안 둘러보기 <ArrowRight size={15} /></Link></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{DESIGN_CONCEPTS.slice(0, 3).map((concept, index) => <div key={concept.id} className={index === 1 ? "mt-10" : ""}><InteriorImage src={concept.imageUrl} alt={concept.title} className="aspect-[.94] rounded-[16px]" /><p className="mt-3 text-[11px] font-semibold text-[#f2eee8]">0{index + 1}. {concept.title}</p><p className="mt-1 text-[10px] text-[#b7afa5]">{concept.subtitle}</p></div>)}</div></div></section>

      <section id="faq" className="mx-auto max-w-[960px] px-5 py-20 sm:px-8 lg:py-28"><div className="text-center"><Eyebrow>FAQ</Eyebrow><h2 className="mt-3 font-display text-[30px] font-semibold tracking-[-.04em] sm:text-[38px]">궁금한 점을 확인해 보세요.</h2></div><div className="mt-10 border-t border-[#dfdad2]">{faq.map(([question, answer], index) => <button key={question} className="w-full border-b border-[#e3ded7] py-5 text-left" onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span className="flex items-center justify-between gap-4"><span className="text-[13px] font-semibold text-[#37332d]">{question}</span><ChevronDown size={17} className={openFaq === index ? "rotate-180 transition-transform" : "transition-transform"} /></span>{openFaq === index && <p className="max-w-2xl pr-8 pt-3 text-[12px] leading-6 text-[#777065]">{answer}</p>}</button>)}</div></section>
    </main>
    <footer className="border-t border-[#e5e0d8] px-5 py-8 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1480px] flex-col gap-3 text-[10px] text-[#938a80] sm:flex-row sm:items-center sm:justify-between"><AppLogo compact /><span>© 2026 INSPIRA. 공간에 새로운 가능성을 더합니다.</span></div></footer>
  </div>;
}

function ProcessCard({ number, icon: Icon, title, desc }: { number: string; icon: typeof UploadCloud; title: string; desc: string }) { return <article className="rounded-[18px] border border-[#e8e3db] bg-white p-6 shadow-[0_8px_22px_rgba(71,57,39,.035)]"><div className="flex items-start justify-between"><span className="font-display text-[19px] text-[#b9ac9d]">{number}</span><span className="grid size-9 place-items-center rounded-xl bg-[#f2eee7] text-[#4d4133]"><Icon size={18} strokeWidth={1.5} /></span></div><h3 className="mt-8 text-[15px] font-bold text-[#332f29]">{title}</h3><p className="mt-3 max-w-xs text-[12px] leading-6 text-[#7c746a]">{desc}</p></article>; }
