/** Quiet Materiality — 정돈된 갤러리 그리드와 프로젝트의 작업 상태를 보여 주는 프로젝트 페이지. */

import { AppShell } from "@/components/AppShell";
import { NewProjectCard, PageTitle, ProjectCard, Tag } from "@/components/InteriorPieces";
import { PROJECTS } from "@/data/mockData";
import { ArrowUpRight, FolderOpen, Search } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

export default function ProjectsPage() { const [query, setQuery] = useState(""); const shown = PROJECTS.filter((project) => project.title.includes(query) || project.roomType.includes(query)); return <AppShell><div className="page-enter mx-auto max-w-[1180px]"><PageTitle eyebrow="02 · 프로젝트" title="공간별 프로젝트를 모아보세요." description="사진, 취향, 생성된 시안과 자재 조합을 프로젝트 단위로 이어서 관리합니다." action={<Link href="/project/new" className="inline-flex items-center gap-2 rounded-xl bg-[#201f1c] px-4 py-3 text-[11px] font-semibold text-white"><span className="grid size-4 place-items-center rounded-full bg-white/15">+</span> 새 프로젝트</Link>} /><div className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><Tag dark>전체 {PROJECTS.length}</Tag><Tag>시안 완료</Tag><Tag>초안</Tag></div><label className="relative block sm:w-[220px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#958d83]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="프로젝트 검색" className="quiet-input pl-9" /></label></div><div className="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 lg:grid-cols-4"><NewProjectCard />{shown.map((project, index) => <ProjectCard key={project.id} project={project} index={index} />)}</div>{shown.length === 0 && <div className="premium-panel mt-8 flex flex-col items-center py-16 text-center"><FolderOpen size={24} className="text-[#9a9085]" /><p className="mt-4 text-[13px] font-semibold">검색 결과가 없어요.</p><button onClick={() => setQuery("")} className="mt-2 text-[11px] text-[#756b60] underline underline-offset-4">검색 초기화</button></div>}<div className="mt-14 rounded-[20px] border border-[#e4ded5] bg-[#efe8dd] p-6 sm:flex sm:items-center sm:justify-between"><div><p className="text-[11px] font-semibold text-[#574b3d]">아직 정리되지 않은 공간이 있나요?</p><p className="mt-1 text-[11px] leading-5 text-[#796c5e]">사진 한 장으로 시작해, 나중에 원하는 방향을 더 구체적으로 입력할 수 있어요.</p></div><Link href="/project/new" className="mt-4 inline-flex items-center gap-1.5 text-[11px] font-bold text-[#40362d] underline underline-offset-4 sm:mt-0">프로젝트 시작하기 <ArrowUpRight size={14} /></Link></div></div></AppShell>; }
