/** Quiet Materiality — 이미지 프레임, 편집 주석, 자재 샘플을 공유하는 고급스러운 UI 조각. */

import { ASSET, MATERIALS } from "@/data/mockData";
import { useInspira } from "@/contexts/InspiraContext";
import { cn } from "@/lib/utils";
import type { DesignConcept, Material, Project } from "@/types/inspira";
import { ArrowUpRight, Check, ChevronRight, Heart, Plus, Sparkles } from "lucide-react";
import { Link } from "wouter";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#938b80]">{children}</p>; }

export function PageTitle({ eyebrow, title, description, action }: { eyebrow?: string; title: React.ReactNode; description?: string; action?: React.ReactNode }) {
  return <div className="mb-8 flex flex-col gap-4 sm:mb-10 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h1 className="mt-2 font-display text-[29px] font-semibold leading-[1.2] tracking-[-0.035em] text-[#25231f] sm:text-[34px]">{title}</h1>{description && <p className="mt-3 max-w-2xl text-[13px] leading-6 text-[#797269] sm:text-sm">{description}</p>}</div>{action && <div className="shrink-0">{action}</div>}</div>;
}

export function Tag({ children, dark = false, className }: { children: React.ReactNode; dark?: boolean; className?: string }) { return <span className={cn("inline-flex items-center rounded-md px-2 py-1 text-[10px] font-medium", dark ? "bg-[#262420] text-white" : "bg-[#efede8] text-[#696159]", className)}>{children}</span>; }

export function IconHeart({ active, onClick, label = "즐겨찾기" }: { active: boolean; onClick: (event: React.MouseEvent<HTMLButtonElement>) => void; label?: string }) { return <button onClick={onClick} aria-label={label} className={cn("grid size-8 place-items-center rounded-full border transition-all active:scale-95", active ? "border-[#2a2925] bg-[#2a2925] text-white" : "border-white/70 bg-white/80 text-[#5f5a52] hover:bg-white")}><Heart size={14} fill={active ? "currentColor" : "none"} /></button>; }

export function InteriorImage({ src, alt, className, priority = false }: { src: string; alt: string; className?: string; priority?: boolean }) { return <div className={cn("overflow-hidden bg-[#e8e1d5]", className)}><img src={src} alt={alt} loading={priority ? "eager" : "lazy"} className="size-full object-cover transition-transform duration-500 ease-out hover:scale-[1.025]" /></div>; }

export function MaterialSwatch({ material, className }: { material: Material; className?: string }) { return <span aria-label={`${material.productName} 샘플`} className={cn("block rounded-md border border-black/[0.04]", className)} style={{ background: material.swatch }} />; }

export function MaterialCompact({ material, reason, showChevron = false }: { material: Material; reason?: string; showChevron?: boolean }) { return <div className="flex gap-3 rounded-xl border-b border-[#eeeae4] py-3.5 last:border-b-0"><MaterialSwatch material={material} className="size-11 shrink-0" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-semibold text-[#342f29]">{material.category}</p><p className="mt-0.5 truncate text-[11px] text-[#6f685f]">{material.brand}</p></div>{showChevron && <ChevronRight size={15} className="mt-1 shrink-0 text-[#aaa398]" />}</div><p className="mt-1 truncate text-[12px] font-medium text-[#292722]">{material.productName}</p><p className="mt-0.5 text-[10px] text-[#968e84]">{material.productCode}</p>{reason && <p className="mt-1.5 line-clamp-2 text-[10px] leading-4 text-[#80786e]">{reason}</p>}</div></div>; }

export function ProjectCard({ project, index = 0 }: { project: Project; index?: number }) {
  const { favoriteProjectIds, toggleFavorite } = useInspira();
  return <article className="group relative min-w-0"><Link href={`/concepts?project=${project.id}`} className="block"><InteriorImage src={project.uploadedImages[0] || ASSET.living} alt={project.title} className="aspect-[1.22] rounded-[14px] shadow-[0_6px_20px_rgba(82,69,50,.08)]" /><div className="pt-3"><div className="flex items-start justify-between gap-2"><h3 className="truncate text-[13px] font-semibold text-[#2c2924]">{project.title}</h3><span className="hidden text-[10px] text-[#9a9288] sm:inline">{project.conceptIds.length}개 시안</span></div><p className="mt-1 text-[10px] text-[#898177]">최근 수정 {project.updatedAt}</p></div></Link><IconHeart active={favoriteProjectIds.includes(project.id)} onClick={(event) => { event.preventDefault(); toggleFavorite("project", project.id); }} label={`${project.title} 즐겨찾기`} /></article>;
}

export function NewProjectCard() { return <Link href="/project/new" className="flex min-h-[165px] flex-col items-center justify-center rounded-[15px] border border-dashed border-[#dcd6cd] bg-[#fcfbf9] px-3 text-center transition-all hover:-translate-y-0.5 hover:border-[#bdb3a6] hover:bg-white"><span className="grid size-10 place-items-center rounded-full border border-[#e4ded5] bg-white text-[#3d3932]"><Plus size={20} /></span><span className="mt-3 text-[12px] font-semibold text-[#3f3a33]">새 프로젝트<br />시작하기</span></Link>; }

export function ConceptCard({ concept, showAction = true, compact = false }: { concept: DesignConcept; showAction?: boolean; compact?: boolean }) {
  const { favoriteConceptIds, toggleFavorite, compareIds, toggleCompare } = useInspira();
  return <article className={cn("group relative overflow-hidden rounded-[18px] border border-[#e9e5de] bg-white shadow-[0_8px_22px_rgba(65,52,38,.045)]", compact && "rounded-[14px]")}><Link href={`/concepts/${concept.id}`} className="block"><div className={cn("relative overflow-hidden", compact ? "aspect-[1.18]" : "aspect-[1.25]")}><InteriorImage src={concept.imageUrl} alt={`${concept.title} 인테리어 시안`} className="size-full" priority={concept.id === "c-01"} /><span className="absolute left-3 top-3 grid size-7 place-items-center rounded-lg bg-white/95 text-[11px] font-semibold text-[#2f2c27] shadow-sm">{concept.id.slice(-2).replace(/^0/, "")}</span></div><div className={cn("p-4", compact && "p-3.5")}><div className="flex items-start justify-between gap-2"><div><h3 className="text-[14px] font-semibold text-[#2e2b26]">{concept.title}</h3><p className="mt-1 line-clamp-2 text-[11px] leading-5 text-[#777066]">{concept.subtitle}</p></div><span className="text-[10px] text-[#978f84]">{concept.score}%</span></div><div className="mt-3 flex flex-wrap gap-1.5">{concept.styleTags.slice(0, 2).map((tag) => <Tag key={tag}>{tag}</Tag>)}</div></div></Link><div className="absolute right-3 top-3"><IconHeart active={favoriteConceptIds.includes(concept.id)} onClick={(event) => { event.preventDefault(); toggleFavorite("concept", concept.id); }} label={`${concept.title} 즐겨찾기`} /></div>{showAction && <div className="flex border-t border-[#eeebe6]"><Link href={`/concepts/${concept.id}`} className="flex flex-1 items-center justify-center gap-1.5 px-3 py-3 text-[11px] font-semibold text-[#39342d] transition-colors hover:bg-[#faf8f5]">상세 보기 <ArrowUpRight size={13} /></Link><button onClick={() => toggleCompare(concept.id)} className={cn("border-l border-[#eeebe6] px-3 text-[10px] font-semibold transition-colors", compareIds.includes(concept.id) ? "bg-[#25231f] text-white" : "text-[#7a7369] hover:bg-[#faf8f5]")}>{compareIds.includes(concept.id) ? <Check size={14} /> : "비교"}</button></div>}</article>;
}

export function MaterialGridCard({ material }: { material: Material }) {
  const { favoriteMaterialIds, toggleFavorite } = useInspira();
  return <article className="group relative rounded-[16px] border border-[#ebe7e0] bg-white p-3 shadow-[0_6px_18px_rgba(65,52,38,.035)]"><MaterialSwatch material={material} className="aspect-[1.25] w-full rounded-[11px]" /><button onClick={() => toggleFavorite("material", material.id)} className="absolute right-5 top-5 grid size-7 place-items-center rounded-full bg-white/85 text-[#6d665d] shadow-sm backdrop-blur transition-colors hover:bg-white"><Heart size={13} fill={favoriteMaterialIds.includes(material.id) ? "currentColor" : "none"} className={favoriteMaterialIds.includes(material.id) ? "text-[#292722]" : ""} /></button><div className="pt-3"><p className="text-[10px] text-[#8e867c]">{material.brand}</p><h3 className="mt-1 min-h-[34px] text-[12px] font-semibold leading-[1.45] text-[#322f29]">{material.productName}</h3><p className="mt-1.5 text-[10px] text-[#978f84]">{material.productCode}</p><div className="mt-3 flex items-center justify-between"><Tag>{material.category}</Tag><span className="text-[10px] text-[#8f877c]">{material.usageCount}회 활용</span></div></div></article>;
}

export function AIChip() { return <span className="inline-flex items-center gap-1 rounded-full border border-[#e3d8c8] bg-[#f6f1e9] px-2.5 py-1 text-[10px] font-semibold text-[#695c4c]"><Sparkles size={11} /> AI 제안</span>; }

export function MiniMaterialRail({ materialIds }: { materialIds: string[] }) { const materials = materialIds.map((id) => MATERIALS.find((material) => material.id === id)).filter(Boolean) as Material[]; return <div className="flex gap-2">{materials.slice(0, 5).map((material) => <div key={material.id} className="flex-1"><MaterialSwatch material={material} className="aspect-square w-full" /><p className="mt-1 truncate text-center text-[8px] text-[#8b8379]">{material.category}</p></div>)}</div>; }
